#!/usr/bin/env python3
"""Generate a deterministic catalog from the current ModernUO skill inventory."""

from __future__ import annotations

import re
from pathlib import Path

import yaml


def load(path: Path) -> dict:
    parts = path.read_text(encoding="utf-8").split("---", 2)
    if len(parts) != 3:
        raise ValueError(f"{path}: invalid frontmatter")
    return yaml.safe_load(parts[1])


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    skills_root = root / "plugins" / "modernuo" / "skills"
    rows = []
    for path in sorted(skills_root.glob("*/SKILL.md")):
        data = load(path)
        desc = re.sub(r"\s+", " ", str(data.get("description", ""))).strip()
        rows.append((str(data.get("name", path.parent.name)), desc))
    lines = ["# Skill Catalog", "", f"Current ModernUO plugin inventory: {len(rows)} skills.", "", "| Skill | Activation boundary |", "|---|---|"]
    lines.extend(f"| `{name}` | {desc.replace('|', '&#124;')} |" for name, desc in rows)
    lines.extend(["", "Generated by `python scripts/generate-skill-catalog.py`.", ""])
    output = skills_root / "SKILL-CATALOG.md"
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"catalog: wrote {output} ({len(rows)} skills)")


if __name__ == "__main__":
    main()
